# Generated by Django 5.0.1 on 2024-01-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0002_chromovies_movie_newchromovies_newlatest_newmovie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=4)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ottapp.customer')),
            ],
        ),
    ]
