# Generated by Django 5.0.1 on 2024-01-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0003_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_profiles', to='ottapp.customer')),
            ],
        ),
    ]
