# Generated by Django 5.0.1 on 2024-01-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0005_alter_customerprofile_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('desc', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('rating', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='avatars/')),
            ],
        ),
    ]
