# Generated by Django 5.0.1 on 2024-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0006_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='media/avatars/'),
        ),
    ]
