# Generated by Django 5.0.1 on 2024-01-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='movies/'),
        ),
    ]
