# Generated by Django 5.0.1 on 2024-01-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0012_moviekid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='link',
        ),
    ]
