# Generated by Django 5.0.1 on 2024-01-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0013_rename_url_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
