# Generated by Django 5.0.1 on 2024-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0014_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
