# Generated by Django 5.0.1 on 2024-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0015_movie_director_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='waste/')),
            ],
        ),
    ]
