# Generated by Django 5.0.1 on 2024-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0016_waste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='url',
        ),
        migrations.AddField(
            model_name='upcoming',
            name='Director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='Duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='Genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
