# Generated by Django 5.0.1 on 2024-01-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0017_remove_upcoming_image1_remove_upcoming_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='rating',
        ),
    ]
